### ISSUE TITLE
Train problems

### ISSUE THREAD

**Issue by Tchuanm** [mustansarfiaz/SCS-Siam#1]
hi,thanks for your great work.
 could u tell me the trianing time? and how much epochs with it .

**Comment by mustansarfiaz** [comment]
thank you for your interest.

I trained the model for 50 epoch and it took around 24hours.

**Comment by Tchuanm** [comment]
> thank you for your interest.
> 
> I trained the model for 50 epoch and it took around 24hours.

thanks~~
